services:
  database:
    image: postgres:latest
    container_name: nti-database
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - nti_postgres_data:/var/lib/postgresql
    ports:
      - '127.0.0.1:5432:5432'

  backend:
    image: ghcr.io/antarux-dev/nti-backend:${VERSION:-latest}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '3000:3000'

volumes:
  nti_postgres_data:
